<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5841c75e2a9b5',
	'title' => 'Hero',
	'fields' => array (
		array (
			'key' => 'field_5841d163ad9b1',
			'label' => 'Crop',
			'name' => 'hero_crop',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Crop the images',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_5841d407ad9b2',
			'label' => 'Slide',
			'name' => 'hero_slide',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Slide',
			'collapsed' => 'field_5841d439ad9b3',
			'sub_fields' => array (
				array (
					'key' => 'field_5841d439ad9b3',
					'label' => 'Title',
					'name' => 'slide_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_5856c879e8756',
					'label' => 'Link',
					'name' => 'slide_link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
				array (
					'key' => 'field_58470ec9edfeb',
					'label' => 'Type',
					'name' => 'slide_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'multiple' => 0,
					'allow_null' => 0,
					'choices' => array (
						'image' => 'Image',
						'video' => 'Video',
					),
					'default_value' => array (
						0 => 'image',
					),
					'ui' => 1,
					'ajax' => 0,
					'placeholder' => '',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_5841d45cad9b4',
					'label' => 'Image',
					'name' => 'slide_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58470ec9edfeb',
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_59a2f6a20b13c',
					'label' => 'Video',
					'name' => 'slide_video_sources',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58470ec9edfeb',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 1,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Add video variation',
					'sub_fields' => array (
						array (
							'key' => 'field_58470704f1790',
							'label' => 'Source',
							'name' => 'video',
							'type' => 'file',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
				array (
					'key' => 'field_59a2f5b90b13b',
					'label' => 'Dimensions',
					'name' => 'slide_video_dimensions',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58470ec9edfeb',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_58470e354ceae',
							'label' => 'Width',
							'name' => 'width',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 1400,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 0,
							'max' => '',
							'step' => '',
						),
						array (
							'key' => 'field_58470e694ceaf',
							'label' => 'Height',
							'name' => 'height',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 350,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 0,
							'max' => '',
							'step' => '',
						),
					),
				),
				array (
					'key' => 'field_59a2f450bbec9',
					'label' => 'Options',
					'name' => 'slide_video_options',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58470ec9edfeb',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_59a2f348c9bc4',
							'label' => 'Autoplay',
							'name' => 'autoplay',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array (
							'key' => 'field_59a2f311c9bc3',
							'label' => 'Mute',
							'name' => 'muted',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array (
							'key' => 'field_59a2f36cc9bc5',
							'label' => 'Loop',
							'name' => 'loop',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
				),
				array (
					'key' => 'field_59a2f2eec9bc2',
					'label' => 'Poster',
					'name' => 'slide_video_poster',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58470ec9edfeb',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5841d4c0ad9b5',
					'label' => 'Overlay color',
					'name' => 'slide_overlay',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'none' => 'None',
						'white' => 'White',
						'black' => 'Black',
					),
					'default_value' => array (
						0 => 'none',
					),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_5841d54dad9b6',
					'label' => 'Theme',
					'name' => 'slide_theme',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'multiple' => 0,
					'allow_null' => 1,
					'choices' => array (
						'boxed' => 'Boxed',
						'cover' => 'Cover',
					),
					'default_value' => array (
						0 => 'cover',
					),
					'ui' => 1,
					'ajax' => 0,
					'placeholder' => '',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_5841d5a7ad9b7',
					'label' => 'Content',
					'name' => 'slide_content',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'new_lines' => 'wpautop',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 4,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'hero',
				'operator' => '==',
			),
		),
	),
	'menu_order' => 40,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
